name: Maven Action Workflow
on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Legend
      run: |
        echo "Execution Date/Time:"
        echo "$(date +'%Y-%m-%d %H:%M:%S')"
    - name: Checkmarx Scan
      env:
        MY_DB_USERNAME: ${{ secrets.MY_DB_USERNAME }}  # If it's a secret
        MY_DB_PASSWORD: ${{ secrets.MY_DB_PASSWORD }}   # If it's a variable set in the environment
      run: printenv 
    - name: Build with Maven
      run: mvn -file pom.xml install -Denv.build.num=1234 -Denv.change.set.num=1234frtt
    - name: Debug Statements
      run: |
        echo "Build with Maven completed successfully..."
        ls -al target

